In [7]:
import numpy as np


a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[  1.34985881  18.17414537  54.59815003]
74.1221542102
[ 0.01821127  0.24519181  0.73659691]


In [8]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [12]:
a = np.array([1010, 1000, 990])
#np.exp(a) / sum(np.exp(a))

c = np.max(a)
b = a - c

np.exp(b) / np.sum(np.exp(b))

array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

In [13]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    
    y = exp_a / sum_exp_a

    return y